spring:
  application:
    name: cardapio-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: false   # we manage schema with Flyway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
