spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardapio
    username: cardapio
    password: cardapio
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.modulith: INFO
    org.flywaydb: INFO
